2018-03-04 00:37:58.766100 {"type":"join","timestamp":1520123878.7661,"network":"irc","server":"freenode","channel":{"uid":"#indieweb-dev","name":"#indieweb-dev"},"author":{"uid":"[eddie]","nickname":"[eddie]","username":"~slackuser","name":null,"photo":"https:\/\/eddiehinkle.com\/images\/profile.jpg","url":"http:\/\/eddiehinkle.com","tz":"US\/Eastern"},"content":null,"modes":[]}
2018-03-04 00:47:46.412700 {"type":"message","timestamp":1520124466.4127,"network":"irc","server":"freenode","channel":{"uid":"#indieweb-dev","name":"#indieweb-dev"},"author":{"uid":"[eddie]","nickname":"[eddie]","username":"~slackuser","name":null,"photo":"https:\/\/eddiehinkle.com\/images\/profile.jpg","url":"http:\/\/eddiehinkle.com","tz":"US\/Eastern"},"content":"!tell [cleverdevil] I used https:\/\/gist.github.com\/cleverdevil\/f33530706d6e8dacd13a8bd8e8c15dba to output a json file and attempted to use https:\/\/gist.github.com\/cleverdevil\/c857695bb2de1e46686d720cad9d124c with that same file. It claims \u201cValueError: No JSON object could be decoded\u201d Did you ever run into that?","modes":[]}
2018-03-04 00:47:46.437500 {"type":"message","timestamp":1520124466.4375,"network":"irc","server":"freenode","channel":{"uid":"#indieweb-dev","name":"#indieweb-dev"},"author":{"uid":"Loqi","nickname":"Loqi","username":"Loqi","name":"Loqi","photo":null,"url":null,"tz":null},"content":"Ok, I'll tell them that when I see them next","modes":[]}
